version: "3"
services:
  web:
    depends_on:
      - php
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
      - ./static:/static
  php:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: PHP.Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWD=$DB_USER_PASSWORD
    volumes:
      - ./app:/app
  schema:
    build:
      context: .
      dockerfile: schema.Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWD=$DB_USER_PASSWORD
    volumes:
      - ./schema:/schema
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_USER_PASSWORD
    healthcheck:
      test: '/usr/bin/mysql --user="${MYSQL_USER}" --password="${MYSQL_PASSWORD}" --execute "SHOW DATABASES;"'
      interval: 3s
      timeout: 1s
      retries: 5
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
