services:
  database:
    build: ./mysql-db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_USER_PASSWORD
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - database
    build: ./php-backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PHP_PORT:3000
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWD=$DB_USER_PASSWORD
      - PORT=$PHP_PORT
    volumes:
      - ./php-backend:/app

volumes:
  db:
  node_modules:
